// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	protos/auth.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
	LogoutRequest
	LogoutResponse
	RefreshRequest
	RefreshResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type LoginResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
}

func (m *LogoutResponse) Reset()                    { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()               {}
func (*LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RefreshRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *RefreshRequest) Reset()                    { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string            { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()               {}
func (*RefreshRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RefreshRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *RefreshResponse) Reset()                    { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string            { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()               {}
func (*RefreshResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RefreshResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "auth.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "auth.LogoutResponse")
	proto.RegisterType((*RefreshRequest)(nil), "auth.RefreshRequest")
	proto.RegisterType((*RefreshResponse)(nil), "auth.RefreshResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	RefreshToken(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/auth.Auth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := grpc.Invoke(ctx, "/auth.Auth/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RefreshToken(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	out := new(RefreshResponse)
	err := grpc.Invoke(ctx, "/auth.Auth/RefreshToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RefreshToken(context.Context, *RefreshRequest) (*RefreshResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RefreshToken(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Auth_Logout_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Auth_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/auth.proto",
}

func init() { proto.RegisterFile("protos/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbd, 0x4e, 0xc3, 0x40,
	0x0c, 0xc7, 0x09, 0x6a, 0x2b, 0xb0, 0x4a, 0x01, 0x53, 0xa4, 0xea, 0x16, 0x50, 0x24, 0x3e, 0xa6,
	0x46, 0x2a, 0x62, 0x64, 0x60, 0x61, 0x62, 0x8a, 0x78, 0x81, 0x54, 0xb8, 0x49, 0x05, 0x89, 0x43,
	0x7c, 0x27, 0x5e, 0x8b, 0x47, 0x44, 0xb9, 0x8f, 0x94, 0xa0, 0x2a, 0x9b, 0xfd, 0xf7, 0xcf, 0xbe,
	0xbf, 0x7d, 0x70, 0x5e, 0x37, 0xac, 0x59, 0x92, 0xcc, 0xe8, 0x62, 0x69, 0x63, 0x1c, 0xb5, 0xb1,
	0xba, 0xca, 0x99, 0xf3, 0x4f, 0x4a, 0xac, 0xb6, 0x36, 0x9b, 0x44, 0x6f, 0x4b, 0x12, 0x9d, 0x95,
	0xb5, 0xc3, 0xe2, 0x17, 0x98, 0xbe, 0x72, 0xbe, 0xad, 0x52, 0xfa, 0x32, 0x24, 0x1a, 0x15, 0x1c,
	0xd5, 0x99, 0xc8, 0x37, 0x37, 0xef, 0x8b, 0xe8, 0x3a, 0xba, 0x3f, 0x4e, 0xbb, 0xbc, 0xad, 0x19,
	0xa1, 0xa6, 0xca, 0x4a, 0x5a, 0x1c, 0xba, 0x5a, 0xc8, 0xe3, 0x1b, 0x38, 0xf1, 0x73, 0xa4, 0xe6,
	0x4a, 0x08, 0xe7, 0x30, 0xd6, 0xfc, 0x41, 0x95, 0x9f, 0xe2, 0x12, 0x8f, 0xb1, 0xd1, 0xe1, 0xbd,
	0xfd, 0xd8, 0x19, 0xcc, 0x02, 0xe6, 0xc6, 0xc5, 0xb7, 0x30, 0x4b, 0x69, 0xd3, 0x90, 0x14, 0xc3,
	0x9d, 0x77, 0x70, 0xda, 0x71, 0x43, 0x4e, 0x56, 0x3f, 0x11, 0x8c, 0x9e, 0x8d, 0x2e, 0x70, 0x05,
	0x63, 0xeb, 0x1c, 0x71, 0x69, 0xcf, 0xf7, 0xf7, 0x1c, 0xea, 0xa2, 0xa7, 0x79, 0x2f, 0x07, 0xf8,
	0x08, 0x13, 0xe7, 0x0f, 0x77, 0xc0, 0x6e, 0x29, 0x35, 0xef, 0x8b, 0x5d, 0xdb, 0x13, 0x4c, 0xbd,
	0xb9, 0xb7, 0xd6, 0x03, 0x7a, 0xae, 0xbf, 0x98, 0xba, 0xfc, 0xa7, 0x86, 0xf6, 0xf5, 0xc4, 0x7e,
	0xd9, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xb4, 0x60, 0x92, 0xee, 0x01, 0x00, 0x00,
}
